name: TestAndBuild

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  npm_config_cache: "/usr/local/npm-cache"
  YARN_CACHE_FOLDER: "/usr/local/npm-cache"

jobs:
#  test:
#    runs-on: self-hosted
#
#    container:
#      image: node:latest
#      volumes:
#        - /usr/local/npm-cache:/usr/local/npm-cache
#        - /var/lib/docker:/var/lib/docker
#
#    steps:
#      - name: Currently Disabled
#        run: echo "Tests are currently disabled."
#
#  #      - name: Checkout repository
#  #        uses: actions/checkout@v3
#  #
#  #      - name: Update Apt
#  #        run: sudo apt update
#  #
#  #      - name: Install NPM
#  #        run: sudo apt install -y npm
#  #
#  #      - name: Clone Ginkou Submodule
#  #        run: git submodule update --init --recursive --remote ginkou
#  #
#  #      - name: Run NPM Install
#  #        run: npm install --prefix ginkou
#  #
#  #      - name: Run NPM Test
#  #        run: npm run test --prefix ginkou


  build:
    runs-on: self-hosted

    container:
      image: node:latest
      volumes:
        - /usr/local/npm-cache:/usr/local/npm-cache
        - /var/lib/docker:/var/lib/docker

#    needs:
#      - ginkou-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Yarn Install
        run: yarn install --prefer-offline

      - name: Run NPM Build
        env:
          BUILD: "development"
        run: npm run build